services:
  devcontainer:
    image: devcontainer:latest
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /workspace
    ports:
      - name: ssh
        protocol: tcp
        app_protocol: ssh
        target: 2222
        published: 2222
      - name: http
        protocol: tcp
        app_protocol: http
        target: 80
      - name: https
        protocol: tcp
        app_protocol: https
        target: 443
      - name: http3
        protocol: udp
        app_protocol: http3
        target: 443
    cap_add:
      - CAP_NET_BIND_SERVICE
    networks:
      - localdev
    working_dir: /workspace
    tty: true

networks:
  localdev:
    driver: bridge
    driver_opts:
      # https://docs.docker.com/network/packet-filtering-firewalls/#setting-the-default-bind-address-for-containers
      "com.docker.network.bridge.host_binding_ipv4": "127.0.0.1"
