[workspace]
resolver = "3"

# TODO: Make visualiser a feature, because it takes some time to compile its dependencies.
members = [
	"bspsuite-buildtasks",
	"bspsuite-core",
	"bspsuite-compiler",
	"bspsuite-ext-goldsrc",
	"bspsuite-extinterface",
	"bspsuite-ffi",
	"bspsuite-visualiser"
]

[workspace.package]
version = "0.1.0"
authors = ["NoodleCollie <noodle.collie@protonmail.com>"]
documentation = "https://example.com/bar"
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.100"
strum = "0.27.2"
log = "0.4.28"
rand = "0.10.2"
glam = { version = "0.30.10", features = ["approx", "serde"] }
clap = { version = "4.5.51", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
