[workspace]
resolver = "3"

members = [
	"bspsuite-buildtasks",
	"bspsuite-core",
	"bspsuite-compiler",
	"bspsuite-ext-goldsrc",
	"bspsuite-extinterface",
	"bspsuite-ffi"
]

[workspace.package]
version = "0.1.0"
authors = ["NoodleCollie <noodle.collie@protonmail.com>"]
documentation = "https://example.com/bar"
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.100"
maths-rs = "0.2.7"
strum = "0.27.2"
log = "0.4.28"
