[bspsuite_dev]
image=docker.io/library/ubuntu:24.04
nvidia=true
home=$HOME/.distrobox/bspsuite_dev
init_hooks=ln -s $HOME/.gitconfig $HOME/.distrobox/bspsuite_dev/.gitconfig

# General deps
additional_packages="git cmake build-essential ninja-build vim gdb"

# Deps for raylib
# Beware: if the wrong Clang package is installed, bindgen can
# fail to find stdarg.h (or other system headers).
additional_packages="mesa-utils mesa-common-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libclang1-20 librust-clang-sys-dev"

# Rust
# Note: install-rust.sh needs to be run manually inside the container.
# I've not yet worked out how to run things as the user from this file.
additional_packages="rustup"

# For Zed (not sure why it needs this?)
additional_packages="libasound2t64"
