[bspsuite_dev]
image=docker.io/library/ubuntu:24.04
nvidia=true

# General deps
additional_packages="git cmake build-essential ninja-build vim gdb"

# Rust
additional_packages="rustup"
init_hooks="rustup default 1.90"

# For correct formatting (see comments in rustfmt.toml)
init_hooks="rustup toolchain install nightly && rustup default stable"

# Deps for raylib
init_hooks="mesa-utils mesa-common-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libclang1-20"
