[package]
name = "bspsuite-extinterface"
description = "Shared types for BSPSuite compiler extensions"

version.workspace = true
authors.workspace = true
documentation.workspace = true
edition.workspace = true

[lib]
name = "bspextifc"
crate-type = ["lib"]

[dependencies]
bspsuite-ffi = { path = "../bspsuite-ffi" }
thin_trait_object = { path = "../thirdparty/thin_trait_object-main-1703d03c32fc10cea50fbe2ec30cd69a387f6845" }
log.workspace = true

[build-dependencies]
serde.workspace = true
toml.workspace = true
regex.workspace = true
const-gen = "1.6.9"
