[package]
name = "bspsuite-compiler"
description = "BSPSuite compiler executable"

version.workspace = true
authors.workspace = true
documentation.workspace = true
edition.workspace = true

[[bin]]
name = "bspc"
path = "src/bspc.rs"

[dependencies]
bspsuite-core = { path = "../bspsuite-core" }
bspsuite-extinterface = { path = "../bspsuite-extinterface" }
clap = { version = "4.5.51", features = ["derive"] }
fern = { version = "0.7.1", features = ["colored"] }
log.workspace = true
paris = { version = "1.5.15", features = ["no_logger"] }
strum = { workspace = true, features = ["derive"] }
lazy_static = "1.5.0"
