[package]
name = "bspsuite-compiler"
description = "BSPSuite compiler executable"

version.workspace = true
authors.workspace = true
documentation.workspace = true
edition.workspace = true

[[bin]]
name = "bspc"
path = "src/bspc.rs"

[dependencies]
bspsuite-ffi = { path = "../bspsuite-ffi" }
bspsuite-core = { path = "../bspsuite-core" }
bspsuite-extinterface = { path = "../bspsuite-extinterface" }
clap.workspace = true
log.workspace = true
lazy_static.workspace = true
fern = { version = "0.7.1", features = ["colored"] }
paris = { version = "1.5.15", features = ["no_logger"] }
strum = { workspace = true, features = ["derive"] }
