name: CI Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build on all platforms
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        BUILD_TARGET: [release]
        os: [ubuntu-22.04, ubuntu-24.04, windows-2022, windows-2025]

    # Monitor this time limit as time goes on.
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      # Required for building raylib
      - name: Install dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: |
          if [ "$RUNNER_OS" == "ubuntu-22.04" ]; then
          	LIBCLANG="libclang1-20"
          else
          	LIBCLANG="libclang1-15"
          fi

          sudo apt update
          sudo apt install \
            build-essential \
            mesa-utils \
            mesa-common-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            "$LIBCLANG" \
            librust-clang-sys-dev

      - name: Build
        run: cargo build --profile ${{ matrix.BUILD_TARGET }} --verbose

      - name: Run tests
        run: cargo test --profile ${{ matrix.BUILD_TARGET }} --verbose
