[bspsuite_dev]
image=docker.io/library/ubuntu:24.04
nvidia=true
home=$HOME/.distrobox/bspsuite_dev

# Volume mappings from host to container
volume=".:$HOME/.distrobox/bspsuite_dev/bspsuite"
volume="$HOME/.gitconfig:/home/$USER/.gitconfig:ro"
volume="$HOME/.ssh:/home/$USER/.ssh:ro"

# General deps
additional_packages="git cmake build-essential ninja-build vim gdb iproute2 net-tools procps"

# SSH deps
additional_packages="ssh openssl ca-certificates"

# Deps for raylib
# Beware: if the wrong Clang package is installed, bindgen can
# fail to find stdarg.h (or other system headers).
additional_packages="mesa-utils mesa-common-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libclang1-20 librust-clang-sys-dev"

# Rust
additional_packages="rustup"

# For Zed (not sure why it needs this?)
additional_packages="libasound2t64"

# Rest of the setup that must run as the local user:
#init_hooks="bash /workspace/.distrobox/root_setup.sh $USER"
#init_hooks="sudo -u $USER /workspace/.distrobox/user_setup.sh"
